builders:
  boringWidgetGeneratorBuilder:
    import: 'package:boring_widget_generator/boring_widget_generator.dart'
    builder_factories: ['boringWidgetGeneratorBuilder']
    auto_apply: dependents
    build_extensions: {".dart":[".boring.dart"]}
    build_to: cache #source
    applies_builders: ['source_gen|combining_builder']